# Generated by Django 5.1.15 on 2026-06-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interests_privacy',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferences_privacy',
        ),
    ]
