# Generated by Django 5.1.15 on 2026-06-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='stranger_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
