# Generated by Django 5.1.15 on 2026-06-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='priority',
            field=models.IntegerField(default=5),
        ),
    ]
